# .streamlit/secrets.toml
# อัปโหลดไฟล์นี้ไปที่ Streamlit Cloud → Settings → Secrets

[gcp_service_account]
type = "service_account"
project_id = "roon-management"
private_key_id = "54185426fc208b40a0366f0b14bb7b79bf8dc8cd"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDHLzz2o/GveHJB
5nQyPFXu4fDOgYvr5RhcM/Wo1lCDQ0oqHWWLTz2gOq945gSeV5+BXDEcSuPfQs17
yuD5p/QyNlz7l3Tj/VLQkqbstbVBmvSq89iBlZJHh+Lc6bjrTnjZrKgsMZTqDBJ9
2HSeHhTod4AAsMSe8UfGWKFhEl0r+O6WZdzUzc8fW3FdkoZPD4k6Uq+QNJ3NyqsB
KAQdz+4D2ICJIh4oguuXaGAYLcANKt9FbIWIt2uyUz0BJfW2MWdUdvyKK1Mn3KsQ
NGNfEBKx80HFY9rLKYSCJjWFM5VLK01Dro5lcNDuvIDTioeHQZ3+Ow3dOFhvAYdl
PPHjzoGvAgMBAAECggEAEHzOW44jizD5qDnRbs0ZbI4toYe4qNH3C77N/BKivygl
Q0oupchCjiOoHbul2zjek6spcjGYHjAd6TwtwOH7BThZxwZOSdxQwWy6PjLQ/6QP
fPfKo/iuZJcQxio0lom8LYHXY90bef9+J7DwqkahgsKi3lZuLXKZzIcj80XoCiPK
BBX/sb6ER3NaVUd+qyOMHknJS+xGqDQRJfa85U2PyyGCMSSGB46VgT9fmXOZIie7
4Wf3roCLyuaoLlbqvi2F3+ueAvv53AHUIW16XMDhGGPxxES8d1AKgtsv+uT/dYd0
q7zNmTAVAaxlW/VKEsEHWHcyKN7/Aqc0nNw9nH4wsQKBgQDovZd4gdM87+sZkXca
pIMC7TFBHuOXk5Fi1iBNVokGM4/7pj+GlRCn1Mpok8cDb7DPuBRw6ANPeSxuL1wv
SYs9+1JcU+d6LdTmKwa/ioBU4+DFyPJtqOJm5mFN6D6Ko76S8JYVcq/lnMHfOejA
QTo17d4lX+t3ckUk38FLMAkIMQKBgQDbFybiXbZnRmoRqISYPTTbOGUZMvV2nMEs
czye/BPBI83LCRdf0RRaV0XEcyDP9YhPgRTsrLXryOlgu3ptraw5FsEiznxvrBAd
hb0LtYO5Draa5shVAmqESq/Ldc5SKXI1TS6q5FAL3ppmkGAooBI9Z3FmC0/7uK9d
DVXYW+2P3wKBgChXtMnOty7452enL14O5ia7tq3zDMBZc/oN48uEFHxes7aLOre5
Xwm4eN1nwDd4RM28us5XaTt9ZZYz32bS+K/lwIEAij9DcoPzMVhCSbxtQ6kFDAC2
JYhwpq06dJzThVUzHtDY8GR8p55qC05IAC8Y7EjON6KczB94Kak+ylIBAoGAMX1l
VzT8AxAw3ZRHf2w0CGEQ1URhlk2KhVPymacvfy1rSzXehdJg2pdkNyAahV9dTzhF
VcEdxwk3TpaK7UOR58NwFUC3czJW4ZRYQ9DY1HCyZwNCtZE6JnAIjdkqpfyew9OP
eyLfwg6iqhBq6EJgXGaFgxuDEcWCN27PuXPqkdkCgYEAkL6LYbgVkUyLiqwpYrCO
l0c7AYuv1WFOl7mvx8QHulwKyAKt6VRRa99lj/9aLqf478thCRn904Eb4e08s6DR
JfOhPJuZcplxnGRKagKUorJ0uuUSp3GuVUZo9rMrMHXf0Xp/HAcK6eQlU+3m13gw
23gvxmoFV9TvD+k9obLH9sM=
-----END PRIVATE KEY-----
"""
client_email = "roon-service@roon-management.iam.gserviceaccount.com"
client_id = "106851016691127723422"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/roon-service%40roon-management.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[spreadsheet]
id = "1yNGEsrhdlwJ4rB88hYjNghitmro8MfPc4_9XJKATn1E"
